version: '3.4'

services:
  nifi-production:
    image: 'apache/nifi:latest'
    restart: on-failure
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=Aa123456!Aa123456!
      - NIFI_VARIABLE_REGISTRY_PROPERTIES=./custom-properties/props2.properties
      # - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_HTTP_PORT=8080
    ports:
      # - 8443:8443
      - 8090:8080
      # - 8090:8090
    volumes:
      - C:\Docker\Data\nifi\${PROJECT_PRODUCTION}\database_repository:/opt/nifi/nifi-current/database_repository
      - C:\Docker\Data\nifi\${PROJECT_PRODUCTION}\flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - C:\Docker\Data\nifi\${PROJECT_PRODUCTION}\content_repository:/opt/nifi/nifi-current/content_repository
      - C:\Docker\Data\nifi\${PROJECT_PRODUCTION}\provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - C:\Docker\Data\nifi\${PROJECT_PRODUCTION}\state:/opt/nifi/nifi-current/state
      - C:\Docker\Data\nifi\${PROJECT_PRODUCTION}\logs:/opt/nifi/nifi-current/logs
      # uncomment the next line after copying the /conf directory from the container to your local directory to persist NiFi flows
      # run command in bind mount folder: docker cp <container-name>:/opt/nifi/nifi-current/conf C:\Docker\Data\nifi\${PROJECT_PRODUCTION}\conf
      - C:\Docker\Data\nifi\${PROJECT_PRODUCTION}\conf:/opt/nifi/nifi-current/conf
      # folder for user source
      - C:\Docker\Data\nifi\${PROJECT_PRODUCTION}\_source:/opt/nifi/nifi-current/source
      # folder for user target
      - C:\Docker\Data\nifi\${PROJECT_PRODUCTION}\_target:/opt/nifi/nifi-current/target
      # folder for temp data
      - C:\Docker\Data\nifi\${PROJECT_PRODUCTION}\_temp-data:/opt/nifi/nifi-current/temp-data
    networks:
      - main-production

  nifi-registry-production:
    image: 'apache/nifi-registry:latest'
    restart: on-failure
    ports:
      - 18081:18080
    volumes:
      # uncomment the next line after copying the /conf directory from the container to your local directory to persist Nifi-Regsitry data
      # run command in bind mount folder: docker cp <container-name>:opt/nifi-registry/nifi-registry-current/conf C:\Docker\Data\nifi-registry\${PROJECT_PRODUCTION}\conf
      - C:\Docker\Data\nifi-registry\${PROJECT_PRODUCTION}\conf:/opt/nifi-registry/nifi-registry-current/conf
      - C:\Docker\Data\nifi-registry\${PROJECT_PRODUCTION}\flow-storage:/opt/nifi-registry/nifi-registry-current/flow_storage
      - C:\Docker\Data\nifi-registry\${PROJECT_PRODUCTION}\database:/opt/nifi-registry/nifi-registry-current/database
      - C:\Workspaces\flow_storage\${PROJECT_PRODUCTION}:/opt/nifi-registry/nifi-registry-current/flow_storage
    networks:
      - main-production

networks:
  main-production:
